### ISSUE TITLE
Main

### ISSUE THREAD

**Issue by BoshraM** [OlenaReukova/react-travel-and-tour-website#4]

**Comment by BoshraM** [comment]
@OlenaReukova  app.css file line 62 should be background

**Comment by BoshraM** [comment]
I need help with some css , line 80 which is container, the items are not centred

**Comment by OlenaReukova** [comment]
@BoshraM "app.css file line 62 should be background"

could you explain?

![Image](https://github.com/OlenaReukova/react-travel-and-tour-website/assets/34659641/e3d811f9-cffc-4159-8649-5182e47665bb)

**Comment by OlenaReukova** [comment]
@mickeyhaile2 What do you think about it?

**Comment by OlenaReukova** [comment]
@BoshraM just to check

**Comment by OlenaReukova** [comment]
@MohammadSefidgar have a look
